# Generated by Django 5.1.1 on 2024-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['NavId'], 'verbose_name': 'Navegación', 'verbose_name_plural': 'Navegaciones'},
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='DeleteAt',
        ),
        migrations.AddField(
            model_name='navigation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='CreateAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='NavId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='PageName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pagína'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='UpdateAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Acualización'),
        ),
    ]
