# Generated by Django 5.1.1 on 2024-10-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0004_alter_navigation_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False)),
                ('ImageUrl', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
