# Generated by Django 5.1.1 on 2024-10-11 14:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0009_remove_news_created_by_remove_news_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalnews',
            fields=[
                ('NewID', models.IntegerField(blank=True, db_index=True)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('image', models.TextField(max_length=100, null=True)),
                ('ImageUrl', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('CreateAt', models.DateTimeField(blank=True, editable=False)),
                ('UpdateAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical news',
                'verbose_name_plural': 'historical newss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
