# Generated by Django 5.1.1 on 2024-10-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0010_historicalnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnews',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='historicalnews',
            old_name='ImageUrl',
            new_name='TextAlt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ImageUrl',
            new_name='TextAlt',
        ),
    ]
