# Generated by Django 5.1.1 on 2024-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0011_rename_image_historicalnews_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnews',
            name='Content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Image',
            field=models.TextField(max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='TextAlt',
            field=models.CharField(max_length=255, verbose_name='Texto Alternativo'),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(null=True, upload_to='articles', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='news',
            name='TextAlt',
            field=models.CharField(max_length=255, verbose_name='Texto Alternativo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
