# Generated by Django 5.1.1 on 2024-10-11 18:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0014_logo_historicallogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='missionValues',
            fields=[
                ('missionValuesID', models.AutoField(primary_key=True, serialize=False)),
                ('Title_mission', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content_value', models.TextField(verbose_name='Contenido')),
                ('Title_value', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content_mission', models.TextField(verbose_name='Contenido')),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='whoWeAre',
            fields=[
                ('whoWeAreID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content', models.TextField(verbose_name='Contenido')),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalmissionValues',
            fields=[
                ('missionValuesID', models.IntegerField(blank=True, db_index=True)),
                ('Title_mission', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content_value', models.TextField(verbose_name='Contenido')),
                ('Title_value', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content_mission', models.TextField(verbose_name='Contenido')),
                ('CreateAt', models.DateTimeField(blank=True, editable=False)),
                ('UpdateAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mission values',
                'verbose_name_plural': 'historical mission valuess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalwhoWeAre',
            fields=[
                ('whoWeAreID', models.IntegerField(blank=True, db_index=True)),
                ('Title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('Content', models.TextField(verbose_name='Contenido')),
                ('CreateAt', models.DateTimeField(blank=True, editable=False)),
                ('UpdateAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical who we are',
                'verbose_name_plural': 'historical who we ares',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
