# Generated by Django 5.1.1 on 2024-10-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0015_missionvalues_whoweare_historicalmissionvalues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='DeleteAt',
        ),
        migrations.AddField(
            model_name='historicalnews',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
