# Generated by Django 5.1.1 on 2024-10-11 21:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0018_navigation_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalnavigation',
            fields=[
                ('NavId', models.IntegerField(blank=True, db_index=True, verbose_name='ID')),
                ('PageName', models.CharField(blank=True, max_length=255, verbose_name='Pagína')),
                ('Url', models.CharField(max_length=255)),
                ('CreateAt', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('UpdateAt', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha Acualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Navegación',
                'verbose_name_plural': 'historical Navegaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
