# Generated by Django 5.1.1 on 2024-10-16 01:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0021_banner_historicalbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('Event', models.CharField(max_length=255, verbose_name='Titulo del evento')),
                ('Address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion del evento')),
                ('EventDate', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='event', verbose_name='Imagen Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalevent',
            fields=[
                ('EventID', models.IntegerField(blank=True, db_index=True)),
                ('Event', models.CharField(max_length=255, verbose_name='Titulo del evento')),
                ('Address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion del evento')),
                ('EventDate', models.DateField()),
                ('Image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
