# Generated by Django 5.1.1 on 2024-10-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0022_event_historicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='TextAlt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='TextAlt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo'),
        ),
    ]
