# Generated by Django 5.1.1 on 2024-10-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0024_alter_event_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Imagen Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Imagen Evento'),
        ),
    ]
