# Generated by Django 5.1.1 on 2024-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0025_alter_banner_image_alter_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='educations',
            options={'verbose_name': 'Educación', 'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='historicalbanner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Banner', 'verbose_name_plural': 'historical Banner'},
        ),
        migrations.AlterModelOptions(
            name='historicaleducations',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Educación', 'verbose_name_plural': 'historical Educación'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Evento', 'verbose_name_plural': 'historical Evento'},
        ),
        migrations.AlterModelOptions(
            name='historicallogo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Logo', 'verbose_name_plural': 'historical Logo'},
        ),
        migrations.AlterModelOptions(
            name='historicalmissionvalues',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Misión y Valores', 'verbose_name_plural': 'historical Misión y Valores'},
        ),
        migrations.AlterModelOptions(
            name='historicalnavigation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Navegación', 'verbose_name_plural': 'historical Navegacion'},
        ),
        migrations.AlterModelOptions(
            name='historicalnews',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Noticias', 'verbose_name_plural': 'historical Noticias'},
        ),
        migrations.AlterModelOptions(
            name='historicalwhoweare',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Quiénes Somos', 'verbose_name_plural': 'historical Quiénes Somos'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterModelOptions(
            name='missionvalues',
            options={'verbose_name': 'Misión y Valores', 'verbose_name_plural': 'Misión y Valores'},
        ),
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['NavId'], 'verbose_name': 'Navegación', 'verbose_name_plural': 'Navegacion'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Noticias', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='whoweare',
            options={'verbose_name': 'Quiénes Somos', 'verbose_name_plural': 'Quiénes Somos'},
        ),
        migrations.AddField(
            model_name='banner',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(null=True, upload_to='articles/', verbose_name='Imagen'),
        ),
    ]
