# Generated by Django 5.1.1 on 2024-10-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0026_alter_banner_options_alter_educations_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='historicalbanner',
            name='Description',
        ),
    ]
