# Generated by Django 5.1.1 on 2024-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0027_remove_banner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
