# Generated by Django 5.1.1 on 2024-10-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0028_banner_description_historicalbanner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FuturoCiertoContent.navigation', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='historicalbanner',
            name='Url',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FuturoCiertoContent.navigation', verbose_name='URL'),
        ),
    ]
