# Generated by Django 5.1.1 on 2024-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0030_rename_content_value_historicalmissionvalues_content_objetive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_mission',
            field=models.TextField(verbose_name='Contenido Misión'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_motivation',
            field=models.TextField(null=True, verbose_name='Contenido Motivación'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Content_objetive',
            field=models.TextField(verbose_name='Contenido Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Title_mission',
            field=models.CharField(max_length=255, verbose_name='Titulo Misión'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Title_motivation',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo Motivación'),
        ),
        migrations.AlterField(
            model_name='historicalmissionvalues',
            name='Title_objetive',
            field=models.CharField(max_length=255, verbose_name='Titulo Objetivo'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_mission',
            field=models.TextField(verbose_name='Contenido Misión'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_motivation',
            field=models.TextField(null=True, verbose_name='Contenido Motivación'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Content_objetive',
            field=models.TextField(verbose_name='Contenido Objetivo'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Title_mission',
            field=models.CharField(max_length=255, verbose_name='Titulo Misión'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Title_motivation',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo Motivación'),
        ),
        migrations.AlterField(
            model_name='missionvalues',
            name='Title_objetive',
            field=models.CharField(max_length=255, verbose_name='Titulo Objetivo'),
        ),
    ]
