# Generated by Django 5.1.1 on 2024-11-06 14:36

import django.db.models.deletion
import helper.image_processing
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0033_collaborator_historicalcollaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('VideoFile', models.FileField(upload_to='videos/', validators=[helper.image_processing.validateVideo])),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Image',
            field=models.ImageField(upload_to='collobator/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborator',
            name='Image',
            field=models.TextField(max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalcollaborator',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Historicalvideo',
            fields=[
                ('VideoID', models.IntegerField(blank=True, db_index=True)),
                ('Title', models.CharField(max_length=255)),
                ('VideoFile', models.TextField(max_length=100, validators=[helper.image_processing.validateVideo])),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical video',
                'verbose_name_plural': 'historical videos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
