# Generated by Django 5.1.1 on 2024-11-07 09:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0034_video_alter_collaborator_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reflectionByJose',
            fields=[
                ('ReflectionID', models.AutoField(primary_key=True, serialize=False)),
                ('Reflection', models.CharField(max_length=255, verbose_name='Refleccion')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Imagen ')),
                ('TextAlt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reflección',
                'verbose_name_plural': 'Reflección',
            },
        ),
        migrations.CreateModel(
            name='HistoricalreflectionByJose',
            fields=[
                ('ReflectionID', models.IntegerField(blank=True, db_index=True)),
                ('Reflection', models.CharField(max_length=255, verbose_name='Refleccion')),
                ('Image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen ')),
                ('TextAlt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Reflección',
                'verbose_name_plural': 'historical Reflección',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
