# Generated by Django 5.1.1 on 2024-11-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0035_reflectionbyjose_historicalreflectionbyjose'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreflectionbyjose',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='reflectionbyjose',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo'),
        ),
    ]
