# Generated by Django 5.1.1 on 2024-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0036_historicalreflectionbyjose_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreflectionbyjose',
            name='Reflection',
            field=models.TextField(verbose_name='Refleccion'),
        ),
        migrations.AlterField(
            model_name='reflectionbyjose',
            name='Reflection',
            field=models.TextField(verbose_name='Refleccion'),
        ),
    ]
