# Generated by Django 5.1.1 on 2024-11-08 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0037_alter_historicalreflectionbyjose_reflection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreflectionbyjose',
            name='Comment1',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalreflectionbyjose',
            name='Comment2',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalreflectionbyjose',
            name='Comment3',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AddField(
            model_name='reflectionbyjose',
            name='Comment1',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AddField(
            model_name='reflectionbyjose',
            name='Comment2',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AddField(
            model_name='reflectionbyjose',
            name='Comment3',
            field=ckeditor.fields.RichTextField(default='Comments', max_length=300),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
