# Generated by Django 5.1.1 on 2024-11-11 15:28

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0041_alter_historicalreflectionbyjose_comment1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=255, verbose_name='Telefono')),
                ('Email', models.CharField(max_length=255)),
                ('LinkFacebook', models.CharField(max_length=255)),
                ('LinkInstagram', models.CharField(max_length=255)),
                ('LinkTweeter', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.AlterField(
            model_name='educations',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='historicaleducations',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.CreateModel(
            name='Historicalcontact',
            fields=[
                ('ContactID', models.IntegerField(blank=True, db_index=True)),
                ('Phone', models.CharField(max_length=255, verbose_name='Telefono')),
                ('Email', models.CharField(max_length=255)),
                ('LinkFacebook', models.CharField(max_length=255)),
                ('LinkInstagram', models.CharField(max_length=255)),
                ('LinkTweeter', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contacto',
                'verbose_name_plural': 'historical Contacto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
