# Generated by Django 5.1.1 on 2024-11-14 02:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0042_contact_alter_educations_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('curreycID', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=100, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='accountBank',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Bank', models.CharField(max_length=255, verbose_name='Banco')),
                ('Account', models.CharField(max_length=255, null=True, verbose_name='Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('CurrencyType', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='FuturoCiertoContent.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Monda',
                'verbose_name_plural': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='HistoricalaccountBank',
            fields=[
                ('AccountID', models.IntegerField(blank=True, db_index=True)),
                ('Bank', models.CharField(max_length=255, verbose_name='Banco')),
                ('Account', models.CharField(max_length=255, null=True, verbose_name='Cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('CurrencyType', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FuturoCiertoContent.currency', verbose_name='Currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Monda',
                'verbose_name_plural': 'historical Moneda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcurrency',
            fields=[
                ('curreycID', models.IntegerField(blank=True, db_index=True)),
                ('currency', models.CharField(max_length=100, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hidden', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Contacto',
                'verbose_name_plural': 'historical Contacto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
