# Generated by Django 5.1.1 on 2024-11-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0043_currency_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='curreycID',
            new_name='CurreycID',
        ),
        migrations.RenameField(
            model_name='historicalcurrency',
            old_name='currency',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='historicalcurrency',
            old_name='curreycID',
            new_name='CurreycID',
        ),
    ]
