# Generated by Django 5.1.1 on 2024-11-14 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0044_rename_currency_currency_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbank',
            options={'verbose_name': 'Cuenta de Banco', 'verbose_name_plural': 'Cuenta de Banco'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccountbank',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cuenta de Banco', 'verbose_name_plural': 'historical Cuenta de Banco'},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='CurreycID',
            new_name='CurrencyID',
        ),
        migrations.RenameField(
            model_name='historicalcurrency',
            old_name='CurreycID',
            new_name='CurrencyID',
        ),
        migrations.AlterField(
            model_name='accountbank',
            name='CurrencyType',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='FuturoCiertoContent.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='historicalaccountbank',
            name='CurrencyType',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FuturoCiertoContent.currency', verbose_name='Moneda'),
        ),
    ]
