# Generated by Django 5.1.1 on 2024-11-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0045_alter_accountbank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Moneda'},
        ),
        migrations.AlterModelOptions(
            name='historicalcurrency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Moneda', 'verbose_name_plural': 'historical Moneda'},
        ),
    ]
