# Generated by Django 5.1.1 on 2024-11-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturoCiertoContent', '0046_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbank',
            old_name='CurrencyType',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='historicalaccountbank',
            old_name='CurrencyType',
            new_name='Currency',
        ),
    ]
