name: Deploy to Azure Slot

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que quieras usar como disparador

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura Node.js (si usas React, Angular, etc.)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Cambia según la versión que uses

    # 3. Instala dependencias (si aplican)
    - name: Install dependencies
      run: npm install

    # 4. Construye la aplicación
    - name: Build the project
      run: npm run build

    # 5. Despliega al slot en Azure App Service
    - name: Deploy to Azure Slot
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: ${{ secrets.AZURE_SLOT_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
