name: Deploy Django API to Azure Slot

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que quieras usar como disparador

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Cambia según la versión que uses

    # 3. Instala dependencias de Python
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecuta migraciones de base de datos (opcional)
    - name: Run database migrations
      run: |
        source venv/bin/activate
        python manage.py migrate

    # 5. Recopila archivos estáticos (si aplica)
    - name: Collect static files
      run: |
        source venv/bin/activate
        python manage.py collectstatic --noinput

    # 6. Despliega al slot en Azure App Service
    - name: Deploy to Azure Slot
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: ${{ secrets.AZURE_SLOT_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
