name: Deploy to Azure

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que desees utilizar como disparador

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usa la versión de Python que tu proyecto requiere

    # 3. Instala las dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Despliega la aplicación a Azure
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Nombre de tu nueva App Service
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
